# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topanalytics', '0002_auto_20170817_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_TopChretien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_alt', models.CharField(blank=True, max_length=25)),
                ('profile_picture', models.ImageField(upload_to=b'profile_picture')),
            ],
        ),
    ]
