# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topanalytics', '0002_auto_20170817_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_TopChretien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=25, unique=True)),
                ('topuser_id', models.CharField(blank=True, max_length=254, unique=True)),
                ('profile_picture', models.CharField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
