# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topanalytics', '0003_meta_topchretien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta_topchretien',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='meta_topchretien',
            name='user_alt',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
